version: '3.7'

services:
  web:
    build: .
    command: sh -c "./wait-for db:5432 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./project/.env
    environment:
      - SECRET_KEY='${SECRET_KEY}'
    depends_on:
      - db

  db:
      image: postgres:latest
      volumes:
        - postgres_data:/var/lib/postgresql_dev/data/
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${postgresql}
        - POSTGRES_DB=${postgresql}

volumes:
  postgres_data: