# Generated by Django 4.2.4 on 2023-08-06 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('fact', models.TextField()),
            ],
            options={
                'verbose_name': 'Fun Fact',
            },
        ),
        migrations.AddConstraint(
            model_name='funfact',
            constraint=models.UniqueConstraint(fields=('month', 'day'), name='funfact_month_day_uniq_constraint'),
        ),
    ]
